filetype off
call pathogen#runtime_append_all_bundles()
filetype plugin indent on

set nocompatible

" Security
set modelines=0

" Tabs/spaces
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" Basic options
set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set relativenumber
set undofile
set undodir=/tmp

" Backups
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/.vim/tmp/swap//   " swap files
set backup                        " enable backups

" Leader
let mapleader = ","
let maplocalleader = "."

" Searching
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch
set gdefault
map <leader><space> :let @/=''<cr>
runtime macros/matchit.vim
nmap <tab> %
vmap <tab> %

" Soft/hard wrapping
set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=85

set list
if has('gui_running')
  set listchars=tab:.\ ,eol:¬
else
  set listchars=tab:.\ ,eol:$
endif

" Color scheme (terminal)
syntax on
set background=dark
colorscheme solarized

"  Use Pathogen to load bundles
call pathogen#runtime_append_all_bundles()

" NERD Tree
" map <F2> :NERDTreeToggle<cr>
let NERDTreeIgnore=['.vim$', '\~$', '.*\.pyc$', 'pip-log\.txt$']

set pastetoggle=<F2>

" Use the damn hjkl keys
"nnoremap <up> <nop>
"nnoremap <down> <nop>
"nnoremap <left> <nop>
"nnoremap <right> <nop>
"
" And make them fucking work, too.
"nnoremap j gj
"nnoremap k gk
"
" Easy buffer navigation
"map <C-h> <C-w>h
"map <C-j> <C-w>j
"map <C-k> <C-w>k
"map <C-l> <C-w>l
"map <leader>w <C-w>v<C-w>l


" Folding
set foldlevelstart=0
nnoremap <Space> za
vnoremap <Space> za
au BufNewFile,BufRead *.html map <leader>ft Vatzf

nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

function! MyFoldText()
  let line = getline(v:foldstart)

  let nucolwidth = &fdc + &number * &numberwidth
  let windowwidth = winwidth(0) - nucolwidth - 3
  let foldedlinecount = v:foldend - v:foldstart

  " expand tabs into spaces
  let onetab = strpart('          ', 0, &tabstop)
  let line = substitute(line, '\t', onetab, 'g')

  let line = strpart(line, 0, windowwidth - 2 -len(foldedlinecount))
  let fillcharcount = windowwidth - len(line) - len(foldedlinecount) - 4
  return line . '.' . repeat(" ",fillcharcount) . foldedlinecount . '.' . ' '
endfunction
set foldtext=MyFoldText()

" Fuck you, help key.
inoremap <F1> <ESC>:set invfullscreen<CR>a
nnoremap <F1> :set invfullscreen<CR>
vnoremap <F1> :set invfullscreen<CR>

" Various syntax stuff
au BufNewFile,BufRead *.less set filetype=less
au BufRead,BufNewFile *.scss set filetype=scss

au BufNewFile,BufRead *.m*down set filetype=markdown
au BufNewFile,BufRead *.m*down nnoremap <leader>1 yypVr=
au BufNewFile,BufRead *.m*down nnoremap <leader>2 yypVr-
au BufNewFile,BufRead *.m*down nnoremap <leader>3 I### <ESC>

" Clean whitespace
map <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

" Ack
map <leader>a :Ack

" Yankring
nnoremap <silent> <F3> :YRShow<cr>
nnoremap <silent> <leader>y :YRShow<cr>

" Formatting, TextMate-style
map <leader>q gqip

nmap <leader>m :make<cr>


" Easier linewise reselection
map <leader>v V`]

" Faster Esc
" inoremap <Esc> <nop>
inoremap jj <ESC>

" Rainbows!
nmap <leader>R :RainbowParenthesesToggle<CR>

" Shouldn't need shift
nnoremap ; :

" Save when losing focus
au FocusLost * :wa

if (&term == 'xterm' || &term =~? '^screen')
    "256 color --
    let &t_Co=256
    " restore screen after quitting
    set t_ti=ESC7ESC[rESC[?47h t_te=ESC[?47lESC8
    if has("terminfo")
        let &t_Sf="\ESC[3%p1%dm"
        let &t_Sb="\ESC[4%p1%dm"
    else
        let &t_Sf="\ESC[3%dm"
        let &t_Sb="\ESC[4%dm"
    endif
endif


nnoremap <leader>w <C-w>v<C-w>l

nnoremap <leader><leader> <C-^>

if has("macunix")
  set fuopt=maxvert,maxhorz
"  set guifont=DejaVu\ Sans\ Mono:h14
  set guifont=Inconsolata:h14
  "  let vimclojure#WantNailgun = 1 
  "  let vimclojure#NailgunClient = "/Users/gavin/.vim/bundle/vimclojure-2.2.0/lib/nailgun/ng"
else
  set guifont=Inconsolata\ 12
endif

set antialias
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R


